use std::{fs, thread};
use std::path::Path;
use std::process::Command;
use std::time::Duration;
use test_finder::test_finder;
use assert_cmd::prelude::*;

fn run_system_test(name: &Path) {
    let output = Command::new("./target/debug/crush")
        .args(&[name.to_str().unwrap()])
        .output()
        .expect("failed to execute process");
    let output_name = name.with_extension("crush.output");
    let expected_output = fs::read_to_string(output_name.to_str().unwrap()).expect(
        format!(
            "failed to read output file {}",
            output_name.to_str().unwrap()
        )
        .as_str(),
    );
    let expected_lines = expected_output.lines().collect::<Vec<&str>>();
    let actual_string = String::from_utf8_lossy(&output.stdout);
    let actual_lines = actual_string.lines().collect::<Vec<&str>>();

    for (idx, (expected, actual)) in expected_lines.iter().zip(actual_lines.iter()).enumerate() {
        assert_eq!(
            actual,
            expected,
            "Error on line {} of output while running file {}.",
            idx+1,
            name.to_str().unwrap()
        );
    }
    
}

#[test]
fn test_nothing() {
    // This empty test only exists to make sure IDEs will realize that there are tests to run in
    // this file. All the real tests are generated by the test_finder macro below.
}


#[test]
fn test_grpc() {
    let run = escargot::CargoBuild::new()
        .bin("grpc-service")
        .package("grpc-service") // Name of the sub-crate
        .run()
        .expect("Failed to build grpc-service binary");



    let mut server = Command::new(run.path())
        .spawn()
        .expect("Failed to start gRPC service");

    // 2. Give the server a moment to bind and listen
    thread::sleep(Duration::from_millis(500));

    // 3. Run your gRPC client test logic here...

    // 4. Clean up the process
    let _ = server.kill();
    let _ = server.wait();
}

test_finder!();
