use std::{fs, thread};
use std::path::Path;
use std::process::Command;
use std::time::Duration;
use test_finder::test_finder;
use assert_cmd::prelude::*;

fn run_system_test(name: &Path) {
    let output = Command::new("./target/debug/crush")
        .args(&[name.to_str().unwrap()])
        .output()
        .expect("failed to execute process");
    let output_name = name.with_extension("crush.output");
    let expected_output = fs::read_to_string(output_name.to_str().unwrap()).expect(
        format!(
            "failed to read output file {}",
            output_name.to_str().unwrap()
        )
        .as_str(),
    );
    let expected_lines = expected_output.lines().collect::<Vec<&str>>();
    let actual_string = String::from_utf8_lossy(&output.stdout);
    let actual_lines = actual_string.lines().collect::<Vec<&str>>();

    for (idx, (expected, actual)) in expected_lines.iter().zip(actual_lines.iter()).enumerate() {
        assert_eq!(
            actual,
            expected,
            "Error on line {} of output while running file {}.",
            idx+1,
            name.to_str().unwrap()
        );
    }

    // The loop above only compares the overlapping prefix, via zip(), so it can't by
    // itself catch a run that produces a different number of lines than expected (e.g.
    // one that now errors out partway through and produces fewer lines, or that emits
    // unexpected trailing output). Check the lengths too.
    assert_eq!(
        actual_lines.len(),
        expected_lines.len(),
        "Wrong number of output lines while running file {}. Expected {} lines, got {}.\n\
         Expected output:\n{}\nActual output:\n{}",
        name.to_str().unwrap(),
        expected_lines.len(),
        actual_lines.len(),
        expected_output,
        actual_string,
    );
}

#[test]
fn test_nothing() {
    // This empty test only exists to make sure IDEs will realize that there are tests to run in
    // this file. All the real tests are generated by the test_finder macro below.
}

/// Asserts that `run_system_test` correctly detects a mismatch and panics for the given
/// fixture. Used to prove run_system_test's line-by-line comparison actually catches a
/// difference in the *number* of lines, not just a difference within the lines both
/// outputs happen to share.
fn assert_run_system_test_panics(name: &Path, description: &str) {
    let result = std::panic::catch_unwind(|| run_system_test(name));
    assert!(
        result.is_err(),
        "expected run_system_test to detect a mismatch and panic, but it did not ({})",
        description,
    );
}

// run_system_test compares expected vs. actual output via
// `expected_lines.iter().zip(actual_lines.iter())`, which stops at the shorter of the two
// -- so a script whose actual output has a different *number* of lines than expected, but
// whose overlapping lines are otherwise identical, is silently accepted today. These
// fixtures (tests/harness/too_{few,many}_lines.crush{,.output}) are deliberately built
// that way: not auto-discovered by test_finder! since it only scans the top-level tests/
// directory, not subdirectories.
#[test]
fn test_run_system_test_catches_missing_trailing_lines() {
    assert_run_system_test_panics(
        Path::new("tests/harness/too_few_lines.crush"),
        "actual output has fewer lines than expected",
    );
}

#[test]
fn test_run_system_test_catches_extra_trailing_lines() {
    assert_run_system_test_panics(
        Path::new("tests/harness/too_many_lines.crush"),
        "actual output has more lines than expected",
    );
}


// See tests/error_handling/last_command_error.crush for the full explanation. In short:
// when the last command in a pipeline errors before ever sending output, job.rs still
// unconditionally tries to receive from its (by-then sender-less) output channel,
// producing a second, unrelated "receiving on an empty and disconnected channel" error
// that leaks an implementation detail and drowns out the real one. This only checks
// stderr content, not the exit status -- whether a failing last command should also
// change the process's exit code is a separate, deliberately unresolved question.
#[test]
fn test_last_command_error_does_not_leak_a_stray_channel_error() {
    let output = Command::new("./target/debug/crush")
        .args(&["tests/error_handling/last_command_error.crush"])
        .output()
        .expect("failed to execute process");

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        !stderr.is_empty(),
        "expected the real conversion error to still be printed, got empty stderr"
    );
    assert!(
        !stderr.contains("disconnected channel"),
        "the real error (about the failed conversion) should be the only error printed; \
         a second, unrelated channel-disconnection error should not leak through.\n\
         Stderr was:\n{}",
        stderr,
    );
}

// See tests/error_handling/schedule_exhausted_input.crush for the full explanation. In
// short: schedule's piped-input branch propagates ordinary stream exhaustion (a
// disconnected channel, which is the *only* thing a disconnect on this pipe can mean) as
// a hard error instead of treating it like every other stream consumer in the codebase
// does. Once fixed, exhausting the input should be silent -- no error at all.
#[test]
fn test_schedule_does_not_leak_a_stray_channel_error_on_exhausted_input() {
    let output = Command::new("./target/debug/crush")
        .args(&["tests/error_handling/schedule_exhausted_input.crush"])
        .output()
        .expect("failed to execute process");

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.is_empty(),
        "expected exhausting schedule's piped input to be silent, got stderr:\n{}",
        stderr,
    );
}

// See tests/error_handling/uniq_unhashable_type.crush for the full explanation. In
// short: deduplicating on an unhashable type (Struct) used to hit a panic guard inside
// Value::hash() directly, because uniq.rs never checked is_hashable() first the way
// sort.rs does for is_comparable(). Fixed to check per-value at runtime (a select
// closure's output column is always statically $any, so the unhashable type only shows
// up at runtime) and return a graceful error instead. A panicking worker thread and a
// graceful CrushResult::Err both leave stdout empty, so this can only be distinguished
// via stderr, not a plain stdout diff.
#[test]
fn test_uniq_does_not_panic_on_unhashable_type() {
    let output = Command::new("./target/debug/crush")
        .args(&["tests/error_handling/uniq_unhashable_type.crush"])
        .output()
        .expect("failed to execute process");

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        !stderr.contains("panicked"),
        "expected a graceful error, not a panic, got stderr:\n{}",
        stderr,
    );
    assert!(
        !stderr.is_empty(),
        "expected a graceful error to still be printed, got empty stderr"
    );
}

#[test]
fn test_grpc() {
    let run = escargot::CargoBuild::new()
        .bin("grpc-service")
        .package("grpc-service") // Name of the sub-crate
        .run()
        .expect("Failed to build grpc-service binary");

    let mut server = Command::new(run.path())
        .spawn()
        .expect("Failed to start gRPC service");

    // Give the server a moment to bind and listen
    thread::sleep(Duration::from_millis(500));

    // Run the crush gRPC client against the server: send a fully populated `Blob` message
    // to the streaming `Mirror` RPC and verify every field comes back unchanged. See
    // tests/grpc/mirror.crush for the actual test logic; it prints a MIRROR_TEST_RESULT
    // marker rather than relying on the process exit code, since `crush:exit` can't
    // reliably terminate a script that still has an open gRPC connection in flight.
    let output = Command::new("./target/debug/crush")
        .args(&["tests/grpc/mirror.crush"])
        .output()
        .expect("failed to execute process");

    let _ = server.kill();
    let _ = server.wait();

    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.contains("MIRROR_TEST_RESULT: PASS"),
        "gRPC Mirror round-trip test did not pass.\nStdout:\n{}\nStderr:\n{}",
        stdout,
        String::from_utf8_lossy(&output.stderr),
    );
}

test_finder!();
