[package]
name = "grpc-service"
version = "0.1.0"
edition = "2024"
authors = ["Axel Liljencrantz <liljencranz@gmail.com>"]
publish = false

[dependencies]
tonic = "0.12"
prost = "0.13"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tonic-reflection = "0.12"
tokio-stream = { version = "0.1", features = ["net"] }

[build-dependencies]
tonic-build = "0.12"
