/**
Tests for the argument-binding algorithm generated by the `#[signature(...)]` macro
(defined in the `signature` crate, see `signature/src/lib.rs` and
`signature/src/signature.rs`). That macro generates the `parse()` method used by every
builtin command in this codebase, but has no tests of its own -- a proc-macro crate can
only export macros, so anything that actually *uses* `#[signature(...)]` has to live in a
crate that depends on it, which in practice means here.

These tests construct minimal signature structs and feed them hand-built `Vec<Argument>`
inputs directly, bypassing the parser entirely -- the same approach `src/lang/argument.rs`
already uses for a handful of signature tests (allowed values, `Option`, `#[default(...)]`,
`Vec` collection, `#[named]` collection). This file goes further, specifically targeting
the binding *order* rules: how named vs. unnamed arguments interact, and in particular how
an `#[unnamed()]` collector field (a `Vec<T>` that greedily consumes every remaining
unnamed argument) affects fields declared before and after it in the struct -- a subtlety
that had no coverage at all before this file.

Per instruction, this file only adds tests -- no production code changes, even where a
test below turned up something surprising.
*/

use crate::lang::argument::Argument;
use crate::lang::ast::source::{Source, SourceType};
use crate::lang::errors::CrushResult;
use crate::lang::ordered_string_map::OrderedStringMap;
use crate::lang::state::contexts::CommandContext;
use crate::lang::value::Value;
use signature::signature;
use std::sync::Arc;

fn dummy(_context: CommandContext) -> CrushResult<()> {
    Ok(())
}

fn src() -> Source {
    Source::new(SourceType::Input, Arc::from(""))
}

fn unnamed(value: Value) -> Argument {
    Argument::unnamed(value, &src())
}

fn named(name: &str, value: Value) -> Argument {
    Argument::named(name, value, &src())
}

// ---------------------------------------------------------------------------
// Baseline: positional binding order and named/unnamed interaction, matching what
// docs/language_reference.md documents: "First, all named arguments are assigned.
// Then, each unnamed argument is assigned to the first parameter that doesn't
// already have a value."
// ---------------------------------------------------------------------------

#[signature(dummy)]
struct TwoScalars {
    a: i128,
    b: String,
}

#[test]
fn unnamed_args_bind_in_declaration_order() {
    let (printer, _) = crate::lang::printer::init(None);
    let parsed = TwoScalars::parse(
        vec![unnamed(Value::Integer(1)), unnamed(Value::from("x"))],
        &printer,
    )
    .unwrap();
    assert_eq!(parsed.a, 1);
    assert_eq!(parsed.b, "x");
}

#[test]
fn named_argument_fills_its_slot_so_unnamed_fills_what_remains() {
    let (printer, _) = crate::lang::printer::init(None);
    let parsed = TwoScalars::parse(
        vec![named("b", Value::from("named-b")), unnamed(Value::Integer(7))],
        &printer,
    )
    .unwrap();
    assert_eq!(parsed.a, 7);
    assert_eq!(parsed.b, "named-b");
}

#[signature(dummy)]
struct ThreeScalars {
    a: i128,
    b: i128,
    c: i128,
}

#[test]
fn unnamed_args_skip_slots_already_filled_by_name() {
    let (printer, _) = crate::lang::printer::init(None);
    let parsed = ThreeScalars::parse(
        vec![
            named("b", Value::Integer(20)),
            unnamed(Value::Integer(1)),
            unnamed(Value::Integer(3)),
        ],
        &printer,
    )
    .unwrap();
    assert_eq!(parsed.a, 1);
    assert_eq!(parsed.b, 20);
    assert_eq!(parsed.c, 3);
}

#[test]
fn duplicate_named_argument_last_one_wins() {
    let (printer, _) = crate::lang::printer::init(None);
    let parsed = TwoScalars::parse(
        vec![
            named("a", Value::Integer(1)),
            named("a", Value::Integer(2)),
            unnamed(Value::from("x")),
        ],
        &printer,
    )
    .unwrap();
    assert_eq!(parsed.a, 2);
}

#[test]
fn stray_unnamed_argument_errors_when_struct_has_no_collector() {
    let (printer, _) = crate::lang::printer::init(None);
    let result = TwoScalars::parse(
        vec![
            unnamed(Value::Integer(1)),
            unnamed(Value::from("x")),
            unnamed(Value::Integer(99)),
        ],
        &printer,
    );
    assert!(
        result.is_err(),
        "a third unnamed argument should be rejected as stray, not silently dropped"
    );
}

#[test]
fn missing_required_argument_errors_clearly() {
    let (printer, _) = crate::lang::printer::init(None);
    assert!(TwoScalars::parse(vec![unnamed(Value::Integer(1))], &printer).is_err());
}

#[test]
fn unnamed_argument_of_wrong_type_errors_instead_of_silently_coercing() {
    let (printer, _) = crate::lang::printer::init(None);
    let result = TwoScalars::parse(
        vec![unnamed(Value::Bool(true)), unnamed(Value::from("x"))],
        &printer,
    );
    assert!(result.is_err());
}

#[signature(dummy)]
struct BoolFlag {
    #[default(false)]
    verbose: bool,
}

#[test]
fn bool_flag_defaults_to_false_and_can_be_named() {
    let (printer, _) = crate::lang::printer::init(None);
    assert_eq!(
        BoolFlag::parse(vec![], &printer).unwrap().verbose,
        false
    );
    assert_eq!(
        BoolFlag::parse(vec![named("verbose", Value::Bool(true))], &printer)
            .unwrap()
            .verbose,
        true
    );
}

// ---------------------------------------------------------------------------
// #[unnamed()] Vec collector: consumes every remaining unnamed argument greedily.
// ---------------------------------------------------------------------------

#[signature(dummy)]
struct LeadThenCollect {
    first: i128,
    #[unnamed()]
    rest: Vec<String>,
}

#[test]
fn unnamed_collector_takes_everything_left_after_earlier_fields() {
    let (printer, _) = crate::lang::printer::init(None);
    let parsed = LeadThenCollect::parse(
        vec![
            unnamed(Value::Integer(1)),
            unnamed(Value::from("a")),
            unnamed(Value::from("b")),
        ],
        &printer,
    )
    .unwrap();
    assert_eq!(parsed.first, 1);
    assert_eq!(parsed.rest, vec!["a".to_string(), "b".to_string()]);
}

#[test]
fn unnamed_collector_can_be_empty() {
    let (printer, _) = crate::lang::printer::init(None);
    let parsed = LeadThenCollect::parse(vec![unnamed(Value::Integer(1))], &printer).unwrap();
    assert_eq!(parsed.first, 1);
    assert!(parsed.rest.is_empty());
}

#[test]
fn unnamed_collector_can_also_be_fed_by_name() {
    let (printer, _) = crate::lang::printer::init(None);
    let parsed = LeadThenCollect::parse(
        vec![
            unnamed(Value::Integer(1)),
            named("rest", Value::from("named-item")),
        ],
        &printer,
    )
    .unwrap();
    assert_eq!(parsed.first, 1);
    assert_eq!(parsed.rest, vec!["named-item".to_string()]);
}

// ---------------------------------------------------------------------------
// A field declared *after* an #[unnamed()] collector. The collector's mutate code is
// emitted first (struct declaration order), and it drains every remaining unnamed
// argument in a `while !_unnamed.is_empty()` loop -- so by the time a later field's own
// binding code runs, nothing positional is left for it. These tests pin down the
// consequence of that: such a field can only ever be supplied by name.
// ---------------------------------------------------------------------------

#[signature(dummy)]
struct CollectThenRequired {
    #[unnamed()]
    items: Vec<i128>,
    label: String,
}

#[test]
fn field_after_unnamed_collector_can_be_set_by_name() {
    let (printer, _) = crate::lang::printer::init(None);
    let parsed = CollectThenRequired::parse(
        vec![
            unnamed(Value::Integer(1)),
            unnamed(Value::Integer(2)),
            named("label", Value::from("x")),
        ],
        &printer,
    )
    .unwrap();
    assert_eq!(parsed.items, vec![1, 2]);
    assert_eq!(parsed.label, "x");
}

#[test]
fn field_after_unnamed_collector_cannot_be_set_positionally() {
    // `label` is declared after `items`, which is the #[unnamed()] collector. Since
    // `items` greedily drains every remaining unnamed value first, `label` never gets a
    // chance to consume one -- it isn't named here either, so this should fail with a
    // clear "no value provided" error rather than silently taking the last positional
    // value as `label`, or leaving it with some bogus/empty value.
    let (printer, _) = crate::lang::printer::init(None);
    let result = CollectThenRequired::parse(
        vec![
            unnamed(Value::Integer(1)),
            unnamed(Value::Integer(2)),
            unnamed(Value::from("x")),
        ],
        &printer,
    );
    assert!(
        result.is_err(),
        "expected an error since `label` was never named and can't be filled \
         positionally after the #[unnamed()] collector"
    );
}

#[signature(dummy)]
struct CollectThenDefaulted {
    #[unnamed()]
    items: Vec<i128>,
    #[default("fallback")]
    label: String,
}

#[test]
fn field_after_unnamed_collector_with_default_falls_back_rather_than_stealing_a_positional_value() {
    // Same shape as CollectThenRequired, but `label` has a default. Does giving it a
    // default let it "reach past" the collector and grab a positional value anyway, or
    // does it just fall back to its default like the required case falls back to an
    // error? (The generated code for a defaulted field after a collector *is* still
    // emitted, unlike the required case -- but the collector has already drained
    // `_unnamed` by the time that code runs, so the expectation here is that it always
    // falls back to the default, never actually consuming a positional value.)
    let (printer, _) = crate::lang::printer::init(None);
    let parsed = CollectThenDefaulted::parse(
        vec![
            unnamed(Value::Integer(1)),
            unnamed(Value::Integer(2)),
            unnamed(Value::Integer(3)),
        ],
        &printer,
    )
    .unwrap();
    assert_eq!(parsed.items, vec![1, 2, 3]);
    assert_eq!(
        parsed.label, "fallback",
        "label should fall back to its default, since the collector already consumed \
         every positional argument before label's own binding code ever runs"
    );
}

#[test]
fn field_after_unnamed_collector_with_default_can_still_be_set_by_name() {
    let (printer, _) = crate::lang::printer::init(None);
    let parsed = CollectThenDefaulted::parse(
        vec![unnamed(Value::Integer(1)), named("label", Value::from("explicit"))],
        &printer,
    )
    .unwrap();
    assert_eq!(parsed.items, vec![1]);
    assert_eq!(parsed.label, "explicit");
}

// ---------------------------------------------------------------------------
// #[named()] collector (OrderedStringMap<T>) does *not* set the same flag an
// #[unnamed()] collector does, so a field declared after it can still bind positionally.
// This mirrors the real shape of control::for's `For` struct (`#[named()] iterator:
// OrderedStringMap<Value>` followed by a plain positional `body: Command`), which relies
// on exactly this behavior in production.
// ---------------------------------------------------------------------------

#[signature(dummy)]
struct NamedCollectorThenPositional {
    #[named()]
    extra: OrderedStringMap<Value>,
    body: String,
}

#[test]
fn field_after_named_collector_can_still_bind_positionally() {
    let (printer, _) = crate::lang::printer::init(None);
    let parsed = NamedCollectorThenPositional::parse(
        vec![named("i", Value::Integer(5)), unnamed(Value::from("the-body"))],
        &printer,
    )
    .unwrap();
    assert_eq!(parsed.body, "the-body");
    let extra = parsed.extra.into_iter().collect::<Vec<_>>();
    assert_eq!(extra.len(), 1);
    assert_eq!(extra[0].0, "i");
    assert!(extra[0].1 == Value::Integer(5));
}

#[test]
fn named_collector_gathers_every_unmatched_named_argument() {
    let (printer, _) = crate::lang::printer::init(None);
    let parsed = NamedCollectorThenPositional::parse(
        vec![
            named("foo", Value::from("a")),
            named("bar", Value::from("b")),
            unnamed(Value::from("body-value")),
        ],
        &printer,
    )
    .unwrap();
    assert_eq!(parsed.body, "body-value");
    let extra = parsed.extra.into_iter().collect::<Vec<_>>();
    assert_eq!(extra.len(), 2);
    assert_eq!(extra[0].0, "foo");
    assert!(extra[0].1 == Value::from("a"));
    assert_eq!(extra[1].0, "bar");
    assert!(extra[1].1 == Value::from("b"));
}

#[test]
fn named_collector_can_be_empty() {
    let (printer, _) = crate::lang::printer::init(None);
    let parsed = NamedCollectorThenPositional::parse(
        vec![unnamed(Value::from("only-body"))],
        &printer,
    )
    .unwrap();
    assert_eq!(parsed.body, "only-body");
    assert!(parsed.extra.into_iter().collect::<Vec<_>>().is_empty());
}
