[package]
name = "signature"
version = "0.1.0"
authors = ["Axel Liljencrantz <liljencranz@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.98", features = [ "full"] }
quote = "1.0.3"
proc-macro2 = "1.0.10"
